source :rubygems

gem 'jwt'
gem 'sinatra'
gem 'json'
gem 'omniauth'
gem 'omniauth-oauth2'
gem 'omniauth-github'
gem 'omniauth-ldap'
gem 'omniauth-facebook'

gem 'net-ldap'
gem 'haml'

# gem 'omniauth-att', :path => File.expand_path("./../../omniauth-att", __FILE__)

gem 'thin'
#group :development do
# gem 'shotgun'
#end

group :development, :test do
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-bundler'
  gem 'growl'
  gem 'rb-fsevent'
end